### ISSUE TITLE
Attempted to load class "SmsaWebServiceException"

### ISSUE THREAD

**Issue by mohamedyasser** [alhoqbani/smsa-webservice#3]
> Attempted to load class "SmsaWebServiceException" from namespace "Alhoqbani\SmsaWebService\Exceptions".
Did you forget a "use" statement for another namespace?

**Comment by alhoqbani** [comment]
Could you provide mire details? How did you get this error?

**Comment by mohamedyasser** [comment]
it's happened when I'm trying to create new shipment using createShipment method and sending wrong date

**Comment by alhoqbani** [comment]
I can't reproduce this error.

Are you using composer to install and load this package?
